CREATE TABLE IF NOT EXISTS genre (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS rating_mpa (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL,
        description varchar
);

CREATE TABLE IF NOT EXISTS films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL,
        description varchar NOT NULL,
        release_date date,
        duration integer,
        rating_mpa_id integer,
        CONSTRAINT fk_rating_mpa FOREIGN KEY(rating_mpa_id)
		  REFERENCES rating_mpa(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				email varchar NOT NULL,
				login varchar NOT NULL,
				name varchar,
				birthday date
);

CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER,
    film_id INTEGER,
    CONSTRAINT fk_user FOREIGN KEY(user_id)
		  REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT fk_film FOREIGN KEY(user_id)
		  REFERENCES films(id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friendship (
    initiator_id INTEGER,
    acceptor_id INTEGER,
	status boolean,
	CONSTRAINT fk_user_initiator FOREIGN KEY(initiator_id)
		  REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT fk_user_acceptor FOREIGN KEY(acceptor_id)
		  REFERENCES users(id) ON DELETE CASCADE,
	PRIMARY KEY (initiator_id,  acceptor_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    genre_id INTEGER,
    film_id INTEGER,
    CONSTRAINT fk_genre FOREIGN KEY(genre_id)
		  REFERENCES genre(id) ON DELETE CASCADE,
	CONSTRAINT fk_film_g FOREIGN KEY(film_id)
		  REFERENCES films(id) ON DELETE CASCADE,
	PRIMARY KEY (genre_id, film_id)
);

-- Справочник жанров
INSERT INTO GENRE (name) VALUES ('Комедия');
INSERT INTO GENRE (name) VALUES ('Драма');
INSERT INTO GENRE (name) VALUES ('Мультфильм');
INSERT INTO GENRE (name) VALUES ('Триллер');
INSERT INTO GENRE (name) VALUES ('Документальный');
INSERT INTO GENRE (name) VALUES ('Боевик');

-- Справочник Рейтинг MPA
INSERT INTO rating_mpa (name, description) VALUES ('G', 'у фильма нет возрастных ограничений');
INSERT INTO rating_mpa (name, description) VALUES ('PG', 'детям рекомендуется смотреть фильм с родителями');
INSERT INTO rating_mpa (name, description) VALUES ('PG-13', 'детям до 13 лет просмотр не желателен');
INSERT INTO rating_mpa (name, description) VALUES ('R', 'лицам до 17 лет просматривать фильм можно только в присутствии взрослого');
INSERT INTO rating_mpa (name, description) VALUES ('NC-17', 'лицам до 18 лет просмотр запрещён');

SELECT * FROM rating_mpa;
COMMIT;